Repository illinois-ceesd/mirgecom, pull requests merged in 2021-07, with the labels that each got.

#418 Replicate call_loopy changes from pyopencl actx base class
  .github/workflows/ci.yaml
  mirgecom/profiling.py
Labels: CI, profiling

#368 Enable CFL and DT
  .ci-support/production-setup.sh
  examples/autoignition-mpi.py
  examples/lump-mpi.py
  examples/mixture-mpi.py
  examples/pulse-mpi.py
  examples/run_examples.sh
  examples/scalar-lump-mpi.py
  examples/sod-mpi.py
  examples/vortex-mpi.py
  mirgecom/inviscid.py
  mirgecom/simutil.py
  test/test_euler.py
Labels: enhancement, y1

#433 Logging: Convert to post LogQuantity
  mirgecom/logging_quantities.py
Labels: logging

#395 Memoize DV on CV
  .ci-support/production-testing-env.sh
  mirgecom/eos.py
  mirgecom/fluid.py
Labels: y1

#446 Laxify the examples
  examples/autoignition-mpi.py
  examples/heat-source-mpi.py
  examples/lump-mpi.py
  examples/mixture-mpi.py
  examples/pulse-mpi.py
  examples/run_examples.sh
  examples/scalar-lump-mpi.py
  examples/vortex-mpi.py
Labels: -y1

#448 Add lazy-compatible Sods shock example
  examples/sod-mpi.py
Labels: -y1

#220 Lazy evaluation
  doc/development/installation.rst
  doc/faq/errors.rst
  doc/index.rst
  doc/running/large-systems.rst
  examples/run_examples.sh
  examples/wave-mpi.py
  examples/wave.py
  mirgecom/initializers.py
  mirgecom/simutil.py
  mirgecom/steppers.py
  test/test_time_integrators.py
Labels: Lazy-eval, enhancement, production-critical, y1

#450 Add lazy examples.
  examples/pulse-mpi-lazy.py
  examples/vortex-mpi-lazy.py
  examples/wave-lazy.py
Labels: Lazy-eval, enhancement

#455 Correct the leap stepper for dt modification
  mirgecom/steppers.py
Labels: bug

#456 Restore vizfile directory handling
  mirgecom/simutil.py
Labels: -y1, enhancement

#457 Correct and test the product rule gradients
  mirgecom/fluid.py
  test/test_fluid.py
Labels: -y1
