Repository illinois-ceesd/mirgecom, pull requests merged in 2021-04, with the labels that each got.

#275 Add inviscid module with inviscid-specific functions
  doc/operators/gas-dynamics.rst
  mirgecom/euler.py
  mirgecom/fluid.py
  mirgecom/inviscid.py
  mirgecom/simutil.py
  test/test_euler.py
Labels: navier-stokes, refactor

#273 Move ConservedVars to fluid module.
  doc/operators/gas-dynamics.rst
  mirgecom/boundary.py
  mirgecom/eos.py
  mirgecom/euler.py
  mirgecom/fluid.py
  mirgecom/initializers.py
  mirgecom/inviscid.py
  mirgecom/simutil.py
  test/test_bc.py
  test/test_eos.py
  test/test_euler.py
  test/test_fluid.py
  test/test_init.py
Labels: navier-stokes, refactor

#272 Add fluid module with resident vel grad function.
  doc/misc.rst
  doc/operators/gas-dynamics.rst
  mirgecom/boundary.py
  mirgecom/eos.py
  mirgecom/euler.py
  mirgecom/fluid.py
  mirgecom/initializers.py
  mirgecom/inviscid.py
  mirgecom/simutil.py
  test/test_bc.py
  test/test_eos.py
  test/test_euler.py
  test/test_fluid.py
  test/test_init.py
Labels: navier-stokes, refactor

#277 Rename inviscid_operator -> euler_operator
  examples/lump-mpi.py
  examples/pulse-mpi.py
  examples/scalar-lump-mpi.py
  examples/sod-mpi.py
  examples/vortex-mpi.py
  mirgecom/euler.py
  test/test_euler.py
Labels: navier-stokes, refactor

#276 Add flux module, inviscid/Euler refactor
  doc/operators/gas-dynamics.rst
  examples/lump-mpi.py
  examples/pulse-mpi.py
  examples/scalar-lump-mpi.py
  examples/sod-mpi.py
  examples/vortex-mpi.py
  mirgecom/euler.py
  mirgecom/flux.py
  test/test_euler.py
Labels: navier-stokes, refactor

#236 Add Pyrometheus thermochemistry EOS
  conda-env.yml
  doc/conf.py
  examples/autoignition-mpi.py
  examples/mixture-mpi.py
  mirgecom/eos.py
  requirements.txt
  test/test_eos.py
Labels: chemistry, mixtures, navier-stokes

#315 CI: install mirgecom branch directly
  .github/workflows/ci.yaml
Labels: CI, emirge

#316 fix CI runs
  .ci-support/install.sh
  .github/workflows/ci.yaml
Labels: CI

#318 skip clone on CI
  .github/workflows/ci.yaml
Labels: CI
