Repository illinois-ceesd/mirgecom, pull requests merged in 2022-08, with the labels that each got.

#718 Bound-preserving limiter
  doc/misc.rst
  doc/operators/gas-dynamics.rst
  examples/autoignition-mpi.py
  mirgecom/limiter.py
  test/test_limiter.py
Labels: enhancement, Production Feeder

#716 field-specific tolerance added by dictionary
  bin/mirgecompare.py
  mirgecom/simutil.py
Labels: mirgecompare

#727 Mirgecompare: check that rank numbers match
  mirgecom/simutil.py
Labels: mirgecompare

#728 Rename `discr` to `dcoll`
  examples/autoignition-mpi.py
  examples/doublemach-mpi.py
  examples/heat-source-mpi.py
  examples/hotplate-mpi.py
  examples/lump-mpi.py
  examples/mixture-mpi.py
  examples/nsmix-mpi.py
  examples/poiseuille-mpi.py
  examples/pulse-mpi.py
  examples/scalar-lump-mpi.py
  examples/sod-mpi.py
  examples/vortex-mpi.py
  examples/wave-mpi.py
  examples/wave.py
  mirgecom/artificial_viscosity.py
  mirgecom/boundary.py
  mirgecom/diffusion.py
  mirgecom/euler.py
  mirgecom/gas_model.py
  mirgecom/initializers.py
  mirgecom/inviscid.py
  mirgecom/io.py
  mirgecom/logging_quantities.py
  mirgecom/navierstokes.py
  mirgecom/operators.py
  mirgecom/simutil.py
  mirgecom/viscous.py
  mirgecom/wave.py
  test/test_av.py
  test/test_bc.py
  test/test_diffusion.py
  test/test_eos.py
  test/test_euler.py
  test/test_filter.py
  test/test_fluid.py
  test/test_init.py
  test/test_inviscid.py
  test/test_lazy.py
  test/test_limiter.py
  test/test_navierstokes.py
  test/test_operators.py
  test/test_restart.py
  test/test_simutil.py
  test/test_symbolic.py
  test/test_viscous.py
  test/test_wave.py
Labels: refactor, Production Feeder
