Repository illinois-ceesd/mirgecom, pull requests merged in 2023-07, with the labels that each got.

#902 Attempt to simplify/generalize coupling
  examples/thermally-coupled-mpi.py
  mirgecom/boundary.py
  mirgecom/multiphysics/__init__.py
  mirgecom/multiphysics/thermally_coupled_fluid_wall.py
  mirgecom/utils.py
  test/test_multiphysics.py
Labels: Production Feeder

#932 add scipy dependency for RTD build
  .rtd-env-py3.yml
Labels: documentation

#938 CI: use mambaforge, uninstall pocl before doc build
  .ci-support/install.sh
  .github/workflows/ci.yaml
Labels: CI
